#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-GladeXML
version:      0.93
version_from: GladeXML.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
